config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"
  devise_for :users, controllers: {
    omniauth_callbacks: "users/omniauth_callbacks",
    sessions: 'users/sessions'
  }
  resources :home
  resources :categories
  resources :films
  resources :countries
end

app/models/actor.rb
class Actor < ApplicationRecord
  has_many :actor_films
  has_many :films, through: :actor_films
end

app/models/actor_film.rb
class ActorFilm < ApplicationRecord
  belongs_to :actor
  belongs_to :film
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  scope :recent, -> { order(id: :desc) }
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :category_films
  has_many :films, through: :category_films
end

app/models/category_film.rb
class CategoryFilm < ApplicationRecord
  belongs_to :category
  belongs_to :film
end

app/models/country.rb
class Country < ApplicationRecord
  has_many :films
end

app/models/episode.rb
class Episode < ApplicationRecord
end

app/models/film.rb
class Film < ApplicationRecord
  FILM_TYPES = [:movie, :series]
  QUANLITY_TYPES = [:HD, :CAM]

  belongs_to :country
  has_many :category_films
  has_many :categories, through: :category_films
  has_many :actor_films
  has_many :actors, through: :actor_films
  has_one_attached :image

  scope :movie, -> { where(film_type: :movie) }
  scope :series, -> { where(film_type: :series) }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: [:facebook]

  def self.new_with_session params, session
    super.tap do |user|
      if data = session["devise.facebook_data"] &&
        session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

  def self.from_omniauth auth
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name
      user.token = auth.credentials.token
      user.expires_at = auth.credentials.expires_at
    end
  end

  def self.koala(auth)
    access_token = auth['token']
    facebook = Koala::Facebook::API.new(access_token)
    facebook.get_object("me?fields=name,picture")
  end

  def self.create_with_omniauth(auth)
    user = find_or_create_by(uid: auth[‘uid’], provider:  auth[‘provider’])
    user.email = “#{auth[‘uid’]}@#{auth[‘provider’]}.com”
    user.password = auth[‘uid’]
    user.name = auth[‘info’][‘name’]
    if User.exists?(user)
      user
    else
      user.save!
      user
    end
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  layout 'admin'

  before_action :authenticate_user!
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def after_sign_in_path_for(resource)
    films_path
  end
end

app/controllers/categories_controller.rb
class CategoriesController < AdminController
  before_action :load_cagegory, only: %i(edit update delete)

  def index
    @categories = Category.all.recent
  end

  def new
    @category = Category.new
  end

  def update
    if @category.update category_params
      redirect_to categories_path
    else
      render :edit
    end
  end

  def delete
    @category.destroy
    redirect_to categories_path
  end

  def create
    @category = Category.create! category_params
    redirect_to new_category_path
  end

  private
  def category_params
    params.require(:category).permit :name
  end

  def load_cagegory
    @category = Category.find params[:id]
  end
end

app/controllers/countries_controller.rb
class CountriesController < AdminController
  before_action :load_country, only: %i(edit update delete)
  def new
    @country = Country.new
  end

  def create
    @country = Country.create! country_params
    redirect_to countries_path
  end

  def update
    if @country.update country_params
      redirect_to countries_path
    else
      render :new
    end
  end

  def delete
    @country.destroy
    redirect_to countries_path
  end

  def index
    @countries = Country.all.recent
  end

  private
  def country_params
    params.require(:country).permit :name
  end

  def load_country
    @country = Country.find params[:id]
  end
end

app/controllers/films_controller.rb
class FilmsController < AdminController
  def index
    @films = Film.all
  end

  def new
    @film = Film.new
    @film.category_films.build
  end

  def create
    ActiveRecord::Base.transaction do
      @film = Film.create! film_params
    end
    redirect_to films_path
  end

  def edit
    @film = Film.find params[:id]
  end

  def update
    @film = Film.find params[:id]
    if @film.update film_params
      redirect_to films_path
    else
      render :edit
    end
  end

  def destroy
    @film = Film.find params[:id]
    @film.destroy
    redirect_to films_path
  end

  private
  def film_params
    params.require(:film).permit :name, :description, :url, :image, :year_release, :country_id, :min_age, :quanlity, :running_time, :rate, :film_type, category_ids: []
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @films = Film.all
  end

  def show
    facebook = Koala::Facebook::API.new(User.first.token)
    @film = Film.find(params[:id])
    @link = facebook.get_object("#{@film.url}?fields=picture,source")["source"]
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  layout "admin"
  # GET /resource/sign_in
  def new
    super
  end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/helpers/films_helper.rb
module FilmsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_item.html.erb
<div class="col-6 col-sm-4 col-lg-3 col-xl-2">
  <div class="card">
    <div class="card__cover card__cover--max-width">
      <%= image_tag film.image if film.image.attached? %>
      <%= link_to home_path(film), class: "card__play" do%>
        <i class="fa fa-play"></i>
      <% end %>
    </div>
    <div class="card__content">
      <h3 class="card__title"><a href="#"><%= film.name %></a></h3>
      <span class="card__category">
        <%= film.categories.pluck(:name).join(", ") %>
      </span>
      <span class="card__rate"><i class="fa fa-star"></i><%= film.rate %></span>
    </div>
  </div>
</div>

app/views/home/_sidebar.html.erb
<div class="col-12 col-lg-4 col-xl-4">
  <div class="row">
    <div class="col-12">
      <h2 class="section__title section__title--sidebar">Phim được đề xuất</h2>
    </div>
    <div class="col-6 col-sm-4 col-lg-6">
      <div class="card">
        <div class="card__cover">
          <%= image_tag "covers/cover" %>
          <a href="#" class="card__play">
            <i class="fa fa-play"></i>
          </a>
        </div>
        <div class="card__content">
          <h3 class="card__title"><a href="#">I Dream in Another Language</a></h3>
          <span class="card__category">
            <a href="#">Action</a>
            <a href="#">Triler</a>
          </span>
          <span class="card__rate"><i class="fa fa-star"></i>8.4</span>
        </div>
      </div>
    </div>
    <div class="col-6 col-sm-4 col-lg-6">
      <div class="card">
        <div class="card__cover">
          <%= image_tag "covers/cover2" %>
          <a href="#" class="card__play">
            <i class="fa fa-play"></i>
          </a>
        </div>
        <div class="card__content">
          <h3 class="card__title"><a href="#">Benched</a></h3>
          <span class="card__category">
            <a href="#">Comedy</a>
          </span>
          <span class="card__rate"><i class="fa fa-star"></i>7.1</span>
        </div>
      </div>
    </div>
    <div class="col-6 col-sm-4 col-lg-6">
      <div class="card">
        <div class="card__cover">
          <%= image_tag "covers/cover3" %>
          <a href="#" class="card__play">
            <i class="fa fa-play"></i>
          </a>
        </div>
        <div class="card__content">
          <h3 class="card__title"><a href="#">Whitney</a></h3>
          <span class="card__category">
            <a href="#">Romance</a>
            <a href="#">Drama</a>
            <a href="#">Music</a>
          </span>
          <span class="card__rate"><i class="fa fa-star"></i>6.3</span>
        </div>
      </div>
    </div>
    <div class="col-6 col-sm-4 col-lg-6">
      <div class="card">
        <div class="card__cover">
          <%= image_tag "covers/cover4" %>
          <a href="#" class="card__play">
            <i class="fa fa-play"></i>
          </a>
        </div>
        <div class="card__content">
          <h3 class="card__title"><a href="#">Blindspotting</a></h3>
          <span class="card__category">
            <a href="#">Comedy</a>
            <a href="#">Drama</a>
          </span>
          <span class="card__rate"><i class="fa fa-star"></i>7.9</span>
        </div>
      </div>
    </div>
    <div class="col-6 col-sm-4 col-lg-6">
      <div class="card">
        <div class="card__cover">
          <%= image_tag "covers/cover5" %>
          <a href="#" class="card__play">
            <i class="fa fa-play"></i>
          </a>
        </div>
        <div class="card__content">
          <h3 class="card__title"><a href="#">I Dream in Another Language</a></h3>
          <span class="card__category">
            <a href="#">Action</a>
            <a href="#">Triler</a>
          </span>
          <span class="card__rate"><i class="fa fa-star"></i>8.4</span>
        </div>
      </div>
    </div>
    <div class="col-6 col-sm-4 col-lg-6">
      <div class="card">
        <div class="card__cover">
          <%= image_tag "covers/cover6" %>
          <a href="#" class="card__play">
            <i class="fa fa-play"></i>
          </a>
        </div>
        <div class="card__content">
          <h3 class="card__title"><a href="#">Benched</a></h3>
          <span class="card__category">
            <a href="#">Comedy</a>
          </span>
          <span class="card__rate"><i class="fa fa-star"></i>7.1</span>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<%= render partial: "layouts/slider" %>
<section class="content">
  <div class="content__head">
    <div class="container">
      <div class="row">
        <div class="col-12">
          <h2 class="content__title">PHIM MỚI</h2>
          <ul class="nav nav-tabs content__tabs" id="content__tabs" role="tablist">
            <li class="nav-item">
              <a class="nav-link active" data-toggle="tab" href="#tab-1" role="tab" aria-controls="tab-1" aria-selected="true">MỚI RA MẮT</a>
            </li>

            <li class="nav-item">
              <a class="nav-link" data-toggle="tab" href="#tab-2" role="tab" aria-controls="tab-2" aria-selected="false">PHIM LẺ</a>
            </li>

            <li class="nav-item">
              <a class="nav-link" data-toggle="tab" href="#tab-3" role="tab" aria-controls="tab-3" aria-selected="false">PHIM BỘ</a>
            </li>
          </ul>
          <div class="content__mobile-tabs" id="content__mobile-tabs">
            <div class="content__mobile-tabs-btn dropdown-toggle" role="navigation" id="mobile-tabs" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <input type="button" value="New items">
              <span></span>
            </div>
            <div class="content__mobile-tabs-menu dropdown-menu" aria-labelledby="mobile-tabs">
              <ul class="nav nav-tabs" role="tablist">
                <li class="nav-item"><a class="nav-link active" id="1-tab" data-toggle="tab" href="#tab-1" role="tab" aria-controls="tab-1" aria-selected="true">NEW RELEASES</a></li>

                <li class="nav-item"><a class="nav-link" id="2-tab" data-toggle="tab" href="#tab-2" role="tab" aria-controls="tab-2" aria-selected="false">MOVIES</a></li>

                <li class="nav-item"><a class="nav-link" id="3-tab" data-toggle="tab" href="#tab-3" role="tab" aria-controls="tab-3" aria-selected="false">TV SERIES</a></li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="container">
    <!-- content tabs -->
    <div class="tab-content" id="myTabContent">
      <div class="tab-pane fade show active" id="tab-1" role="tabpanel" aria-labelledby="1-tab">
        <div class="row">
          <%= render partial: 'home/item', collection: @films.recent, as: :film %>
        </div>
      </div>

      <div class="tab-pane fade" id="tab-2" role="tabpanel" aria-labelledby="2-tab">
        <div class="row">
          <%= render partial: 'home/item', collection: @films.movie.recent, as: :film %>
        </div>
      </div>


      <div class="tab-pane fade" id="tab-3" role="tabpanel" aria-labelledby="2-tab">
        <div class="row">
          <%= render partial: 'home/item', collection: @films.series.recent, as: :film %>
        </div>
      </div>
    </div>
    <!-- end content tabs -->
  </div>
</section>
<%= render partial: "layouts/expected" %>

app/views/home/show.html.erb
	<section class="section details">
    <%= image_tag @film.image, class: 'details__bg' if @film.image.attached? %>
		<div class="container">
			<div class="row">
				<div class="col-12">
					<h1 class="details__title"><%= @film.name %></h1>
				</div>
				<div class="col-12 col-xl-6">
					<div class="card card--details">
						<div class="row">
							<div class="col-12 col-sm-4 col-md-4 col-lg-3 col-xl-5">
								<div class="card__cover card__cover--max-width2">
                  <%= image_tag @film.image if @film.image.attached? %>
								</div>
							</div>
							<div class="col-12 col-sm-8 col-md-8 col-lg-9 col-xl-7">
								<div class="card__content">
									<div class="card__wrap">
										<span class="card__rate"><i class="fa fa-star"></i>8.4</span>

										<ul class="card__list">
											<li><%= @film.quanlity %></li>
											<li><%= @film.min_age %>+</li>
										</ul>
									</div>

									<ul class="card__meta">
										<li><span>Thể loại:</span>
										<a href="#"><%= @film.categories.pluck(:name).join(", ") %></a></li>
										<li><span>Năm ra mắt:</span> <%= @film.year_release %></li>
										<li><span>Thời lượng:</span> <%= @film.running_time %> min</li>
										<li><span>Quốc gia:</span> <a href="#"> <%= @film.country.name %> </a> </li>
									</ul>

									<div class="card__description card__description--details">
										<%= @film.description %>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
				<div class="col-12 col-xl-6">
					<video controls crossorigin playsinline poster="../../../cdn.plyr.io/static/demo/View_From_A_Blue_Moon_Trailer-HD.jpg" id="player">
						<source src="<%= @link %>" type="video/mp4" size="576">
						<source src="https://cdn.plyr.io/static/demo/View_From_A_Blue_Moon_Trailer-720p.mp4" type="video/mp4" size="720">
						<source src="https://cdn.plyr.io/static/demo/View_From_A_Blue_Moon_Trailer-1080p.mp4" type="video/mp4" size="1080">
						<source src="https://cdn.plyr.io/static/demo/View_From_A_Blue_Moon_Trailer-1440p.mp4" type="video/mp4" size="1440">

						<track kind="captions" label="English" srclang="en" src="https://cdn.plyr.io/static/demo/View_From_A_Blue_Moon_Trailer-HD.en.vtt"
						    default>
						<track kind="captions" label="Français" srclang="fr" src="https://cdn.plyr.io/static/demo/View_From_A_Blue_Moon_Trailer-HD.fr.vtt">

						<a href="https://cdn.plyr.io/static/demo/View_From_A_Blue_Moon_Trailer-576p.mp4" download>Download</a>
					</video>
				</div>

				<div class="col-12">
					<div class="details__wrap">
						<div class="details__devices">
							<span class="details__devices-title">Available on devices:</span>
							<ul class="details__devices-list">
								<li><i class="fa fa-apple"></i><span>IOS</span></li>
								<li><i class="fa fa-android"></i><span>Android</span></li>
								<li><i class="fa fa-windows"></i><span>Windows</span></li>
								<li><i class="fa fa-tv"></i><span>Smart TV</span></li>
							</ul>
						</div>
						<div class="details__share">
							<span class="details__share-title">Share with friends:</span>

							<ul class="details__share-list">
								<li class="facebook"><a href="#"><i class="fa fa-facebook"></i></a></li>
								<li class="instagram"><a href="#"><i class="fa fa-instagram"></i></a></li>
								<li class="twitter"><a href="#"><i class="fa fa-twitter"></i></a></li>
								<li class="vk"><a href="#"><i class="fa fa-vk"></i></a></li>
							</ul>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>

	<section class="content">
		<div class="content__head">
			<div class="container">
				<div class="row">
					<div class="col-12">
						<!-- content title -->
						<h2 class="content__title">Discover</h2>
						<!-- end content title -->

						<!-- content tabs nav -->
						<ul class="nav nav-tabs content__tabs" id="content__tabs" role="tablist">
							<li class="nav-item">
								<a class="nav-link active" data-toggle="tab" href="#tab-1" role="tab" aria-controls="tab-1" aria-selected="true">Comments</a>
							</li>

							<li class="nav-item">
								<a class="nav-link" data-toggle="tab" href="#tab-3" role="tab" aria-controls="tab-3" aria-selected="false">Photos</a>
							</li>
						</ul>
						<!-- end content tabs nav -->

						<!-- content mobile tabs nav -->
						<div class="content__mobile-tabs" id="content__mobile-tabs">
							<div class="content__mobile-tabs-btn dropdown-toggle" role="navigation" id="mobile-tabs" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
								<input type="button" value="Comments">
								<span></span>
							</div>

							<div class="content__mobile-tabs-menu dropdown-menu" aria-labelledby="mobile-tabs">
								<ul class="nav nav-tabs" role="tablist">
									<li class="nav-item"><a class="nav-link active" id="1-tab" data-toggle="tab" href="#tab-1" role="tab" aria-controls="tab-1" aria-selected="true">Comments</a></li>

									<li class="nav-item"><a class="nav-link" id="3-tab" data-toggle="tab" href="#tab-3" role="tab" aria-controls="tab-3" aria-selected="false">Photos</a></li>
								</ul>
							</div>
						</div>
						<!-- end content mobile tabs nav -->
					</div>
				</div>
			</div>
		</div>

		<div class="container">
			<div class="row">
				<div class="col-12 col-lg-8 col-xl-8">
					<!-- content tabs -->
					<div class="tab-content" id="myTabContent" style="background: white;">
						<div class="tab-pane fade show active" id="tab-1" role="tabpanel" aria-labelledby="1-tab">
							<div class="row none-margin" >
                <div id="fb-root"></div>
                <script async defer crossorigin="anonymous" src="https://connect.facebook.net/vi_VN/sdk.js#xfbml=1&version=v3.3&appId=213332442606223&autoLogAppEvents=1"></script>
                <div class="fb-comments" data-href="<%= home_url(@film) %>" data-width="" data-numposts="5"></div>
							</div>
						</div>

						<div class="tab-pane fade" id="tab-3" role="tabpanel" aria-labelledby="3-tab">
							<!-- project gallery -->
							<div class="gallery" itemscope>
								<div class="row">
									<!-- gallery item -->
									<figure class="col-12 col-sm-6 col-xl-4" itemprop="associatedMedia" itemscope>
										<a href="img/gallery/project-1.jpg" itemprop="contentUrl" data-size="1920x1280">
                      <%= image_tag "gallery/project-1" %>
										</a>
										<figcaption itemprop="caption description">Some image caption 1</figcaption>
									</figure>
									<!-- end gallery item -->

									<!-- gallery item -->
									<figure class="col-12 col-sm-6 col-xl-4" itemprop="associatedMedia" itemscope>
										<a href="img/gallery/project-2.jpg" itemprop="contentUrl" data-size="1920x1280">
											<%= image_tag "gallery/project-2" %>
										</a>
										<figcaption itemprop="caption description">Some image caption 2</figcaption>
									</figure>
									<!-- end gallery item -->

									<!-- gallery item -->
									<figure class="col-12 col-sm-6 col-xl-4" itemprop="associatedMedia" itemscope>
										<a href="img/gallery/project-3.jpg" itemprop="contentUrl" data-size="1920x1280">
											<%= image_tag "gallery/project-3" %>
										</a>
										<figcaption itemprop="caption description">Some image caption 3</figcaption>
									</figure>
									<!-- end gallery item -->

									<!-- gallery item -->
									<figure class="col-12 col-sm-6 col-xl-4" itemprop="associatedMedia" itemscope>
										<a href="img/gallery/project-4.jpg" itemprop="contentUrl" data-size="1920x1280">
											<%= image_tag "gallery/project-4" %>
										</a>
										<figcaption itemprop="caption description">Some image caption 4</figcaption>
									</figure>
									<!-- end gallery item -->

									<!-- gallery item -->
									<figure class="col-12 col-sm-6 col-xl-4" itemprop="associatedMedia" itemscope>
										<a href="img/gallery/project-5.jpg" itemprop="contentUrl" data-size="1920x1280">
											<%= image_tag "gallery/project-5" %>
										</a>
										<figcaption itemprop="caption description">Some image caption 5</figcaption>
									</figure>
									<!-- end gallery item -->

									<!-- gallery item -->
									<figure class="col-12 col-sm-6 col-xl-4" itemprop="associatedMedia" itemscope>
										<a href="img/gallery/project-6.jpg" itemprop="contentUrl" data-size="1920x1280">
											<%= image_tag "gallery/project-6" %>
										</a>
										<figcaption itemprop="caption description">Some image caption 6</figcaption>
									</figure>
									<!-- end gallery item -->
								</div>
							</div>
							<!-- end project gallery -->
						</div>
					</div>
					<!-- end content tabs -->
				</div>

      <%= render partial: "home/sidebar" %>
			</div>
		</div>
	</section>
	<!-- end content -->

	<!-- Root element of PhotoSwipe. Must have class pswp. -->
	<div class="pswp" tabindex="-1" role="dialog" aria-hidden="true">

		<!-- Background of PhotoSwipe.
		It's a separate element, as animating opacity is faster than rgba(). -->
		<div class="pswp__bg"></div>

		<!-- Slides wrapper with overflow:hidden. -->
		<div class="pswp__scroll-wrap">

			<!-- Container that holds slides. PhotoSwipe keeps only 3 slides in DOM to save memory. -->
			<!-- don't modify these 3 pswp__item elements, data is added later on. -->
			<div class="pswp__container">
				<div class="pswp__item"></div>
				<div class="pswp__item"></div>
				<div class="pswp__item"></div>
			</div>

			<!-- Default (PhotoSwipeUI_Default) interface on top of sliding area. Can be changed. -->
			<div class="pswp__ui pswp__ui--hidden">

				<div class="pswp__top-bar">

					<!--  Controls are self-explanatory. Order can be changed. -->

					<div class="pswp__counter"></div>

					<button class="pswp__button pswp__button--close" title="Close (Esc)"></button>

					<button class="pswp__button pswp__button--fs" title="Toggle fullscreen"></button>

					<!-- Preloader -->
					<div class="pswp__preloader">
						<div class="pswp__preloader__icn">
							<div class="pswp__preloader__cut">
								<div class="pswp__preloader__donut"></div>
							</div>
						</div>
					</div>
				</div>

				<button class="pswp__button pswp__button--arrow--left" title="Previous (arrow left)"></button>

				<button class="pswp__button pswp__button--arrow--right" title="Next (arrow right)"></button>

				<div class="pswp__caption">
					<div class="pswp__caption__center"></div>
				</div>
			</div>
		</div>
	</div>