config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"
  devise_for :users, controllers: {
    omniauth_callbacks: "users/omniauth_callbacks",
    sessions: 'users/sessions'
  }
  resources :home
  resources :categories
  resources :films
  resources :countries
end

app/models/actor.rb
class Actor < ApplicationRecord
  has_many :actor_films
  has_many :films, through: :actor_films
end

app/models/actor_film.rb
class ActorFilm < ApplicationRecord
  belongs_to :actor
  belongs_to :film
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  scope :recent, -> { order(id: :desc) }
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :category_films
  has_many :films, through: :category_films
end

app/models/category_film.rb
class CategoryFilm < ApplicationRecord
  belongs_to :category
  belongs_to :film
end

app/models/country.rb
class Country < ApplicationRecord
  has_many :films
end

app/models/episode.rb
class Episode < ApplicationRecord
end

app/models/film.rb
class Film < ApplicationRecord
  FILM_TYPES = [:movie, :series]
  QUANLITY_TYPES = [:HD, :CAM]

  belongs_to :country
  has_many :category_films
  has_many :categories, through: :category_films
  has_many :actor_films
  has_many :actors, through: :actor_films
  has_one_attached :image

  scope :movie, -> { where(film_type: :movie) }
  scope :series, -> { where(film_type: :series) }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: [:facebook]

  def self.new_with_session params, session
    super.tap do |user|
      if data = session["devise.facebook_data"] &&
        session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

  def self.from_omniauth auth
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name
      user.token = auth.credentials.token
      user.expires_at = auth.credentials.expires_at
    end
  end

  def self.koala(auth)
    access_token = auth['token']
    facebook = Koala::Facebook::API.new(access_token)
    facebook.get_object("me?fields=name,picture")
  end

  def self.create_with_omniauth(auth)
    user = find_or_create_by(uid: auth[‘uid’], provider:  auth[‘provider’])
    user.email = “#{auth[‘uid’]}@#{auth[‘provider’]}.com”
    user.password = auth[‘uid’]
    user.name = auth[‘info’][‘name’]
    if User.exists?(user)
      user
    else
      user.save!
      user
    end
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  layout 'admin'

  before_action :authenticate_user!
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def after_sign_in_path_for(resource)
    films_path
  end
end

app/controllers/categories_controller.rb
class CategoriesController < AdminController
  before_action :load_cagegory, only: %i(edit update delete)

  def index
    @categories = Category.all.recent
  end

  def new
    @category = Category.new
  end

  def update
    if @category.update category_params
      redirect_to categories_path
    else
      render :edit
    end
  end

  def delete
    @category.destroy
    redirect_to categories_path
  end

  def create
    @category = Category.create! category_params
    redirect_to new_category_path
  end

  private
  def category_params
    params.require(:category).permit :name
  end

  def load_cagegory
    @category = Category.find params[:id]
  end
end

app/controllers/countries_controller.rb
class CountriesController < AdminController
  before_action :load_country, only: %i(edit update delete)
  def new
    @country = Country.new
  end

  def create
    @country = Country.create! country_params
    redirect_to countries_path
  end

  def update
    if @country.update country_params
      redirect_to countries_path
    else
      render :new
    end
  end

  def delete
    @country.destroy
    redirect_to countries_path
  end

  def index
    @countries = Country.all.recent
  end

  private
  def country_params
    params.require(:country).permit :name
  end

  def load_country
    @country = Country.find params[:id]
  end
end

app/controllers/films_controller.rb
class FilmsController < AdminController
  def index
    @films = Film.all
  end

  def new
    @film = Film.new
    @film.category_films.build
  end

  def create
    ActiveRecord::Base.transaction do
      @film = Film.create! film_params
    end
    redirect_to films_path
  end

  def edit
    @film = Film.find params[:id]
  end

  def update
    @film = Film.find params[:id]
    if @film.update film_params
      redirect_to films_path
    else
      render :edit
    end
  end

  def destroy
    @film = Film.find params[:id]
    @film.destroy
    redirect_to films_path
  end

  private
  def film_params
    params.require(:film).permit :name, :description, :url, :image, :year_release, :country_id, :min_age, :quanlity, :running_time, :rate, :film_type, category_ids: []
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @films = Film.all
  end

  def show
    facebook = Koala::Facebook::API.new(User.first.token)
    @film = Film.find(params[:id])
    @link = facebook.get_object("#{@film.url}?fields=picture,source")["source"]
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  layout "admin"
  # GET /resource/sign_in
  def new
    super
  end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/helpers/films_helper.rb
module FilmsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/categories/_form.html.erb
<%= simple_form_for @category ,wrapper: :inline_form, html: { class: "form-inline" }, wrapper_mappings: { boolean: :inline_boolean } do |f| %>
  <%= f.input :name, label: 'Category', input_html: { class: "mb-2 mr-sm-2" } %>
  <%= f.button :submit, class: "btn-primary mb-2" %>
<% end %>

app/views/categories/index.html.erb
<%= link_to "Thêm mới", new_category_path, class: "btn btn-success my-2" %>
<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">Tên</th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <th scope="row"><%= category.name %></th>
        <td>
          <%= link_to "Chỉnh sửa", edit_category_path(category), class: "btn btn-light" %>
          <%= link_to "Xóa", category_path(category), class: "btn btn-dark", method: :delete, data: { confirm: "Bạn có chắc chắn muốn xóa danh mục này không? Điều này đồng nghĩa với việc tất cả phim nằm trong danh mục này đều bị xóa" } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/categories/new.html.erb
<%= render partial: '/categories/form' %>

app/views/countries/_form.html.erb
<%= simple_form_for @country ,wrapper: :inline_form, html: { class: "form-inline" }, wrapper_mappings: { boolean: :inline_boolean } do |f| %>
  <%= f.input :name, label: 'Category', input_html: { class: "mb-2 mr-sm-2" } %>
  <%= f.button :submit, class: "btn-primary mb-2" %>
<% end %>

app/views/countries/index.html.erb
<%= link_to "Thêm mới", new_country_path, class: "btn btn-success my-2" %>
<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">Tên</th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
    <% @countries.each do |country| %>
      <tr>
        <th scope="row"><%= country.name %></th>
        <td>
          <%= link_to "Chỉnh sửa", edit_country_path(country), class: "btn btn-light" %>
          <%= link_to "Xóa", country_path(country), class: "btn btn-dark", method: :delete, data: { confirm: "Bạn có chắc chắn muốn xóa quốc gia này không, điều này đồng nghĩa với việc tất cả phim thuộc về quốc gia này sẽ bị xóa?" } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/countries/new.html.erb
<%= render partial: '/countries/form' %>

app/views/films/_form.html.erb
<%= simple_form_for @film do |f| %>
  <%= f.error_notification %>
  <%= f.input :name, label: 'Tên phim' %>
  <%= f.input :country_id, as: :select, collection: Country.all.map{ |a| [a.name, a.id] }, label: "Quốc gia", include_blank: false %>
  <%= f.input :category_ids, as: :check_boxes, collection: Category.all.map{ |a| [a.name, a.id] }, label: "Thể loại" %>
  <%= f.input :film_type, as: :select, collection: Film::FILM_TYPES.map{ |a| [t(a), a] }, label: "Loại phim", include_blank: false %>
  <%= f.input :year_release, label: 'Năm ra mắt' %>
  <%= f.input :running_time, label: 'Thời lượng hoặc số tập' %>
  <%= f.input :quanlity, as: :select, collection: Film::QUANLITY_TYPES.map{ |a| [a, a] }, label: 'Chất lượng', include_blank: false %>
  <%= f.input :rate, label: 'Đánh giá' %>
  <%= f.input :min_age, label: 'Độ tuổi tối thiểu' %>
  <%= f.input :description, label: 'Mô tả' %>
  <%= f.input :url, label: 'url' %>
  <%= f.input :image, as: :file, label: 'Ảnh' %>
  <%= f.button :submit, class: "btn-primary" %>
<% end %>

app/views/films/edit.html.erb
<div class="col-6" style="background: white;">
  <%= render partial: '/films/form' %>
</div>

app/views/films/index.html.erb
<%= link_to "Thêm mới", new_film_path, class: "btn btn-success my-2" %>
<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">Tên</th>
      <th scope="col">Thể loại</th>
      <th scope="col">Quốc gia</th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
    <% @films.each do |film| %>
      <tr>
        <th scope="row"><%= film.name %></th>
        <td><%= film.categories.pluck(:name).join(",") %></td>
        <td><%= film.country.name %></td>
        <td>
          <%= link_to "Chỉnh sửa", edit_film_path(film), class: "btn btn-light" %>
          <%= link_to "Xóa", film_path(film), class: "btn btn-dark", method: :delete, data: { confirm: "Bạn có chắc chắn muốn xóa phim này không?" } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/films/new.html.erb
<div class="col-6" style="background: white;">
  <%= render partial: '/films/form' %>
</div>